const BASE_DIR = "/img/landing";

interface ResponsiveImageProps {
	/** Base file name (without width/extension), e.g. "whatsapp". */
	name: string;
	/** Accessible description of the image. */
	alt: string;
	/** Widths generated by `pnpm optimize:images` for this asset. */
	widths: number[];
	/** CSS `sizes` attribute describing the rendered width across breakpoints. */
	sizes: string;
	/** Intrinsic source width (px) — sets aspect ratio to prevent layout shift. */
	width: number;
	/** Intrinsic source height (px) — sets aspect ratio to prevent layout shift. */
	height: number;
	className?: string;
	/** Load eagerly (above-the-fold). Defaults to lazy. */
	priority?: boolean;
}

/**
 * Renders a responsive <picture> with AVIF (preferred) and WebP sources.
 * Assets are produced by `scripts/optimize-images.mjs`.
 */
export function ResponsiveImage({
	name,
	alt,
	widths,
	sizes,
	width,
	height,
	className,
	priority = false,
}: ResponsiveImageProps) {
	const buildSrcSet = (ext: "avif" | "webp"): string =>
		widths.map((w) => `${BASE_DIR}/${name}-${w}.${ext} ${w}w`).join(", ");

	const fallbackWidth = widths[widths.length - 1];

	return (
		<picture>
			<source type="image/avif" srcSet={buildSrcSet("avif")} sizes={sizes} />
			<source type="image/webp" srcSet={buildSrcSet("webp")} sizes={sizes} />
			<img
				src={`${BASE_DIR}/${name}-${fallbackWidth}.webp`}
				alt={alt}
				width={width}
				height={height}
				loading={priority ? "eager" : "lazy"}
				decoding="async"
				className={className}
			/>
		</picture>
	);
}
