/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as CostRouteImport } from './routes/cost'
import { Route as AppRouteImport } from './routes/app'
import { Route as AcceptableUseRouteImport } from './routes/acceptable-use'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as TrackTokenRouteImport } from './routes/track.$token'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppPosterRouteImport } from './routes/app.poster'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppCheckoutRouteImport } from './routes/app.checkout'
import { Route as AppProductsIndexRouteImport } from './routes/app.products.index'
import { Route as AppOrdersIndexRouteImport } from './routes/app.orders.index'
import { Route as AppCustomersIndexRouteImport } from './routes/app.customers.index'
import { Route as AppProductsNewRouteImport } from './routes/app.products.new'
import { Route as AppProductsImportRouteImport } from './routes/app.products.import'
import { Route as AppProductsProductIdRouteImport } from './routes/app.products.$productId'
import { Route as AppOrdersShortIdRouteImport } from './routes/app.orders.$shortId'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/app.customers.$customerId'
import { Route as AppAdminWabaRouteImport } from './routes/app.admin.waba'
import { Route as AppAdminSellersRouteImport } from './routes/app.admin.sellers'
import { Route as AppAdminBillingRouteImport } from './routes/app.admin.billing'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptableUseRoute = AcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const TrackTokenRoute = TrackTokenRouteImport.update({
  id: '/track/$token',
  path: '/track/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPosterRoute = AppPosterRouteImport.update({
  id: '/poster',
  path: '/poster',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsImportRoute = AppProductsImportRouteImport.update({
  id: '/products/import',
  path: '/products/import',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersShortIdRoute = AppOrdersShortIdRouteImport.update({
  id: '/orders/$shortId',
  path: '/orders/$shortId',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminWabaRoute = AppAdminWabaRouteImport.update({
  id: '/admin/waba',
  path: '/admin/waba',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSellersRoute = AppAdminSellersRouteImport.update({
  id: '/admin/sellers',
  path: '/admin/sellers',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBillingRoute = AppAdminBillingRouteImport.update({
  id: '/admin/billing',
  path: '/admin/billing',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/app': typeof AppRouteWithChildren
  '/cost': typeof CostRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/poster': typeof AppPosterRoute
  '/app/settings': typeof AppSettingsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/track/$token': typeof TrackTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/billing': typeof AppAdminBillingRoute
  '/app/admin/sellers': typeof AppAdminSellersRoute
  '/app/admin/waba': typeof AppAdminWabaRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/orders/$shortId': typeof AppOrdersShortIdRoute
  '/app/products/$productId': typeof AppProductsProductIdRoute
  '/app/products/import': typeof AppProductsImportRoute
  '/app/products/new': typeof AppProductsNewRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/cost': typeof CostRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/poster': typeof AppPosterRoute
  '/app/settings': typeof AppSettingsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/track/$token': typeof TrackTokenRoute
  '/app': typeof AppIndexRoute
  '/app/admin/billing': typeof AppAdminBillingRoute
  '/app/admin/sellers': typeof AppAdminSellersRoute
  '/app/admin/waba': typeof AppAdminWabaRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/orders/$shortId': typeof AppOrdersShortIdRoute
  '/app/products/$productId': typeof AppProductsProductIdRoute
  '/app/products/import': typeof AppProductsImportRoute
  '/app/products/new': typeof AppProductsNewRoute
  '/app/customers': typeof AppCustomersIndexRoute
  '/app/orders': typeof AppOrdersIndexRoute
  '/app/products': typeof AppProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/app': typeof AppRouteWithChildren
  '/cost': typeof CostRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/poster': typeof AppPosterRoute
  '/app/settings': typeof AppSettingsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/track/$token': typeof TrackTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/billing': typeof AppAdminBillingRoute
  '/app/admin/sellers': typeof AppAdminSellersRoute
  '/app/admin/waba': typeof AppAdminWabaRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/orders/$shortId': typeof AppOrdersShortIdRoute
  '/app/products/$productId': typeof AppProductsProductIdRoute
  '/app/products/import': typeof AppProductsImportRoute
  '/app/products/new': typeof AppProductsNewRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/acceptable-use'
    | '/app'
    | '/cost'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/app/checkout'
    | '/app/insights'
    | '/app/poster'
    | '/app/settings'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/track/$token'
    | '/app/'
    | '/app/admin/billing'
    | '/app/admin/sellers'
    | '/app/admin/waba'
    | '/app/customers/$customerId'
    | '/app/orders/$shortId'
    | '/app/products/$productId'
    | '/app/products/import'
    | '/app/products/new'
    | '/app/customers/'
    | '/app/orders/'
    | '/app/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/acceptable-use'
    | '/cost'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/app/checkout'
    | '/app/insights'
    | '/app/poster'
    | '/app/settings'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/track/$token'
    | '/app'
    | '/app/admin/billing'
    | '/app/admin/sellers'
    | '/app/admin/waba'
    | '/app/customers/$customerId'
    | '/app/orders/$shortId'
    | '/app/products/$productId'
    | '/app/products/import'
    | '/app/products/new'
    | '/app/customers'
    | '/app/orders'
    | '/app/products'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/acceptable-use'
    | '/app'
    | '/cost'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/app/checkout'
    | '/app/insights'
    | '/app/poster'
    | '/app/settings'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/track/$token'
    | '/app/'
    | '/app/admin/billing'
    | '/app/admin/sellers'
    | '/app/admin/waba'
    | '/app/customers/$customerId'
    | '/app/orders/$shortId'
    | '/app/products/$productId'
    | '/app/products/import'
    | '/app/products/new'
    | '/app/customers/'
    | '/app/orders/'
    | '/app/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AcceptableUseRoute: typeof AcceptableUseRoute
  AppRoute: typeof AppRouteWithChildren
  CostRoute: typeof CostRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  TrackTokenRoute: typeof TrackTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptable-use': {
      id: '/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/acceptable-use'
      preLoaderRoute: typeof AcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/track/$token': {
      id: '/track/$token'
      path: '/track/$token'
      fullPath: '/track/$token'
      preLoaderRoute: typeof TrackTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/poster': {
      id: '/app/poster'
      path: '/poster'
      fullPath: '/app/poster'
      preLoaderRoute: typeof AppPosterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checkout': {
      id: '/app/checkout'
      path: '/checkout'
      fullPath: '/app/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products/': {
      id: '/app/products/'
      path: '/products'
      fullPath: '/app/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders/': {
      id: '/app/orders/'
      path: '/orders'
      fullPath: '/app/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers/': {
      id: '/app/customers/'
      path: '/customers'
      fullPath: '/app/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products/new': {
      id: '/app/products/new'
      path: '/products/new'
      fullPath: '/app/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products/import': {
      id: '/app/products/import'
      path: '/products/import'
      fullPath: '/app/products/import'
      preLoaderRoute: typeof AppProductsImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products/$productId': {
      id: '/app/products/$productId'
      path: '/products/$productId'
      fullPath: '/app/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders/$shortId': {
      id: '/app/orders/$shortId'
      path: '/orders/$shortId'
      fullPath: '/app/orders/$shortId'
      preLoaderRoute: typeof AppOrdersShortIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers/$customerId': {
      id: '/app/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/app/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/waba': {
      id: '/app/admin/waba'
      path: '/admin/waba'
      fullPath: '/app/admin/waba'
      preLoaderRoute: typeof AppAdminWabaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/sellers': {
      id: '/app/admin/sellers'
      path: '/admin/sellers'
      fullPath: '/app/admin/sellers'
      preLoaderRoute: typeof AppAdminSellersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/billing': {
      id: '/app/admin/billing'
      path: '/admin/billing'
      fullPath: '/app/admin/billing'
      preLoaderRoute: typeof AppAdminBillingRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppPosterRoute: typeof AppPosterRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminBillingRoute: typeof AppAdminBillingRoute
  AppAdminSellersRoute: typeof AppAdminSellersRoute
  AppAdminWabaRoute: typeof AppAdminWabaRoute
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppOrdersShortIdRoute: typeof AppOrdersShortIdRoute
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
  AppProductsImportRoute: typeof AppProductsImportRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCheckoutRoute: AppCheckoutRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppPosterRoute: AppPosterRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminBillingRoute: AppAdminBillingRoute,
  AppAdminSellersRoute: AppAdminSellersRoute,
  AppAdminWabaRoute: AppAdminWabaRoute,
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppOrdersShortIdRoute: AppOrdersShortIdRoute,
  AppProductsProductIdRoute: AppProductsProductIdRoute,
  AppProductsImportRoute: AppProductsImportRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AcceptableUseRoute: AcceptableUseRoute,
  AppRoute: AppRouteWithChildren,
  CostRoute: CostRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  TrackTokenRoute: TrackTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
